// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Data;

namespace ShoppingCart.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210924134246_AddingSeedProducts")]
    partial class AddingSeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoppingCart.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 9, 24, 16, 42, 45, 423, DateTimeKind.Unspecified).AddTicks(5743), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "product 1 description",
                            Image = "//todo",
                            IsDeleted = false,
                            ModifiedAt = new DateTimeOffset(new DateTime(2021, 9, 24, 16, 42, 45, 431, DateTimeKind.Unspecified).AddTicks(5017), new TimeSpan(0, 3, 0, 0, 0)),
                            Name = "Product 1",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 9, 24, 16, 42, 45, 431, DateTimeKind.Unspecified).AddTicks(9474), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "product 2 description",
                            Image = "//todo",
                            IsDeleted = false,
                            ModifiedAt = new DateTimeOffset(new DateTime(2021, 9, 24, 16, 42, 45, 431, DateTimeKind.Unspecified).AddTicks(9512), new TimeSpan(0, 3, 0, 0, 0)),
                            Name = "Product 2",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTimeOffset(new DateTime(2021, 9, 24, 16, 42, 45, 431, DateTimeKind.Unspecified).AddTicks(9605), new TimeSpan(0, 3, 0, 0, 0)),
                            Description = "product 3 description",
                            Image = "//todo",
                            IsDeleted = false,
                            ModifiedAt = new DateTimeOffset(new DateTime(2021, 9, 24, 16, 42, 45, 431, DateTimeKind.Unspecified).AddTicks(9615), new TimeSpan(0, 3, 0, 0, 0)),
                            Name = "Product 3",
                            Price = 300m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
